version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pgadm
    ports:
      - 5432:5432
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    networks:
      database_network:
        ipv4_address: 172.30.0.3
      backend_network: null


  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      backend_network:
        ipv4_address: 172.20.0.3
      frontend_network: null

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    ports:
      - 3010:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,natel-discrete-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      frontend_network:
        ipv4_address: 172.10.0.3

networks:
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1
  backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  database_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1