version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pgadm
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    networks:
      database_network:
        ipv4_address: 172.30.0.3
      backend_network: null

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_DB=0
    volumes:
      - ./volumes/redis-data:/data
     # - ./redis.conf:/etc/redis/redis.conf
    networks:
      database_network:
        ipv4_address: 172.30.0.4
      backend_network: null

  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=90d # 90일보다 오래된 metrics는 삭제
      - --storage.tsdb.retention.size=10GB # 10GB를 넘을 시 오래된 metrics 삭제
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/proemtheus/consoles
      - --web.enable-admin-api
    ports:
      - "9090:9090"
    networks:
      backend_network:
        ipv4_address: 172.20.0.3
      frontend_network: null

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    ports:
      - "3010:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
#    environment:
#      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,natel-discrete-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      frontend_network:
        ipv4_address: 172.10.0.3

networks:
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1
  backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  database_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1