global:
  scrape_interval: 5s

scrape_configs:
#  - job_name: 'postgres'
#    static_configs:
#      - targets: ['db:5432']

  - job_name: 'fcm-actuator'
    metrics_path: '/fcm/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:13119']
