server:
  port: 13009

spring:
  profiles:
    default: "local"
  jackson.default-property-inclusion: non_null
  devtools.livereload.enable: true

management:
  server:
    port: 13119
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: "/fcm/actuator"
      exposure:
        include: "health,prometheus"

---
spring:
  config:
    activate:
      on-profile:
        - "local"
  pid.file: "./config/application.pid"

fcm-apps:
  -
    name: "ecobridge"
    google-application-credentials: "./config/serviceAccountKey-ecobridge.json"
    connection-timeout: 3
    read-timeout: 5
#  -
#    name: dragonballpc
#    google-application-credentials: ./config/serviceAccountKey-dragonballpc.json
#    connection-timeout: 3
#    read-timeout: 5

---
spring:
  config:
    activate:
      on-profile:
        - dev
  pid.file: "./config/application.pid"


fcm-apps:
  -
    name: ecobridge
    google-application-credentials: ./config/serviceAccountKey-ecobridge.json
    connection-timeout: 3
    read-timeout: 5


---
spring:
  config:
    activate:
      on-profile:
        - prod
  pid.file: "./config/application.pid"


fcm-apps:
  -
    name: ecobridge
    google-application-credentials: ./config/serviceAccountKey-ecobridge.json
    connection-timeout: 3
    read-timeout: 5

