server:
  port: 3009

spring:
  jackson.default-property-inclusion: non_null
  devtools.livereload.enable: true


management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring:
  profile: local
  pid.file: ./config/application.pid

fcm-apps:
  -
    name: ecobridge
    google-application-credentials: ./config/serviceAccountKey-ecobridge.json
    connection-timeout: 3
    read-timeout: 5
#  -
#    name: dragonballpc
#    google-application-credentials: ./config/serviceAccountKey-dragonballpc.json
#    connection-timeout: 3
#    read-timeout: 5

---
spring:
  profile: dev
  pid.file: ./config/application.pid

fcm-apps:
  -
    name: ecobridge
    google-application-credentials: ./config/serviceAccountKey-ecobridge.json
    connection-timeout: 3
    read-timeout: 5


---
spring:
  profile: prod
  pid.file: ./config/application.pid

fcm-apps:
  -
    name: ecobridge
    google-application-credentials: ./config/serviceAccountKey-ecobridge.json
    connection-timeout: 3
    read-timeout: 5

