CREATE TABLE IF NOT EXISTS fcm_msg (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  app_name VARCHAR(50) NOT NULL,
  token  VARCHAR(255) NOT NULL,
  send_yn VARCHAR(1) DEFAULT 'N' NOT NULL,
  success_yn VARCHAR(1) DEFAULT 'N' NOT NULL,
  title  VARCHAR(250) NOT NULL,
  body  VARCHAR(4000) NOT NULL,
  image VARCHAR(1024) NOT NULL,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
