server:
  port: 30001

spring:
  jackson.default-property-inclusion: non_null
  devtools.livereload.enable: true

---
spring:
  profile: local
  pid.file: ./application.pid

fcm:
  google-application-credentials: ./serviceAccountKey.json
  connection-timeout: 3
  read-timeout: 5

---
spring:
  profile: dev
  pid.file: ./application.pid

fcm:
  google-application-credentials: ./serviceAccountKey.json
  connection-timeout: 3
  read-timeout: 5

---
spring:
  profile: prod
  pid.file: ./application.pid

fcm:
  google-application-credentials: ./serviceAccountKey.json
  connection-timeout: 3
  read-timeout: 5
